# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- fix/*

pool:
  vmImage: $(imageName)

jobs:
  - job: Clone_job
    steps:
    - script: echo Clone_job
    displayName: 'clone incorrect repo'

  - job: Execute_job
    dependsOn: Clone_job
    condition: failed()
    steps:
    - script: echo Execute job
    displayName: 'echo Execute job name'
