# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- script: echo Building project $(imageName)
  displayName: 'step building project'

- script: echo Testing project $(imageName)
  displayName: 'step testing project'

- script: echo Publishing project $(imageName)
  displayName: 'step publish project'
  
- script: echo Deploying project $(imageName)
  displayName: 'step deploying project'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
