# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: 'Building project'
  displayName: 'step building project'

- script: 'Testing project'
  displayName: 'step testing project'

- script: 'Publishing project'
  displayName: 'step publish project'
  
- script: 'Deploying project'
  displayName: 'step deploying project'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
